controller:
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi

configs:
  jetstream:
    versions:
      - version: latest
        natsImage: nats:2.10
        metricsExporterImage: natsio/prometheus-nats-exporter:0.14.0
        configReloaderImage: natsio/nats-server-config-reloader:0.14.1
        startCommand: /nats-server
