apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-promoter-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-addons
  source:
    repoURL: https://github.com/platform-engineer-lab/platform-addons
    targetRevision: HEAD
    path: manifests/gitops-promoter
  destination:
    name: in-cluster
    namespace: promoter-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
