apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-promoter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: addons
  source:
    repoURL: https://github.com/platform-engineer-lab/platform-addons.git
    targetRevision: HEAD
    path: charts/gitops-promoter
  destination:
    server: https://kubernetes.default.svc
    namespace: promoter-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
