apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: management
            clusterName: in-cluster
          - env: dev
            clusterName: dev
          - env: prod
            clusterName: prod
  template:
    metadata:
      name: 'cert-manager-{{env}}'
    spec:
      project: addons
      sources:
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: 'v1.20.2'
          helm:
            releaseName: cert-manager
            valueFiles:
              - $values/addons/cert-manager/values-base.yaml
              - $values/addons/cert-manager/values-{{env}}.yaml
        - repoURL: https://github.com/platform-engineer-lab/platform-addons.git
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{clusterName}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
