apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-addons
  sources:
    - repoURL: oci://docker.io/envoyproxy
      chart: gateway-helm
      targetRevision: v1.8.1
      helm:
        releaseName: envoy-gateway
        valueFiles:
          - $config/roles/prod/envoy-gateway/default-values.yaml
          - $config/roles/prod/envoy-gateway/prod-values.yaml
    - repoURL: https://github.com/platform-engineer-lab/platform-addons
      targetRevision: HEAD
      ref: config
  destination:
    name: prod
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
