apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: NodePort
        patch:
          type: MergePatch
          value:
            spec:
              ports:
                - name: http-80
                  protocol: TCP
                  port: 80
                  targetPort: 10080
                  nodePort: 30080
