apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-store
  target:
    name: grafana-admin
  data:
    - secretKey: admin-user
      remoteRef:
        key: platform-grafana-admin
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: platform-grafana-admin
        property: admin-password
