apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: platform-addons

  source:
    repoURL: https://github.com/platform-engineer-lab/platform-addons
    targetRevision: HEAD
    path: manifests/kyverno
  destination:
    name: dev
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
